# Cargo.toml


[package]
name = "serde-demo"
version = "0.2.0"
edition = "2021"

[dependencies]
axum = "0.6.10"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
